# Generated by Django 3.2.6 on 2021-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictcrop',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictcrop',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
